-- Migration: Create Translation Subschema
-- This migration creates the `fish_translations` table to support the internationalization
-- architecture (language-first slugs and GIN text search) as defined in the plan.

CREATE TABLE IF NOT EXISTS fish_translations (
    id bigint generated by default as identity primary key,
    fish_id bigint not null references fish(id) on delete cascade,
    language_code varchar(2) not null,
    slug varchar(255) not null,
    name varchar(255) not null,
    common_other_names text[],
    description_general text,
    description_habitat_details text,
    description_care_aquarium text,
    description_social_behavior text,
    description_breeding text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(fish_id, language_code),
    unique(language_code, slug)
);

-- Full-text search index (GIN) for efficient cross-language search
ALTER TABLE fish_translations ADD COLUMN IF NOT EXISTS search_vector tsvector GENERATED ALWAYS AS (
    setweight(to_tsvector('simple', coalesce(name, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(description_general, '')), 'C') ||
    setweight(to_tsvector('simple', coalesce(description_habitat_details, '')), 'D')
) STORED;

CREATE INDEX IF NOT EXISTS fish_translations_search_idx ON fish_translations USING GIN (search_vector);

-- Function to search fish by translation
CREATE OR REPLACE FUNCTION search_fish_by_language(
    search_query text,
    lang_code varchar,
    page_limit int DEFAULT 12,
    page_offset int DEFAULT 0
) RETURNS TABLE (
    fish_id bigint,
    slug varchar,
    name varchar,
    latin_name varchar,
    rank real
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        f.id,
        t.slug,
        t.name,
        f.latin_name,
        ts_rank(t.search_vector, to_tsquery('simple', search_query || ':*')) as rank
    FROM fish f
    JOIN fish_translations t ON f.id = t.fish_id
    WHERE t.language_code = lang_code
      AND (search_query = '' OR t.search_vector @@ to_tsquery('simple', search_query || ':*'))
    ORDER BY rank DESC
    LIMIT page_limit
    OFFSET page_offset;
END;
$$ LANGUAGE plpgsql;
